### ISSUE TITLE
object 'tmpnames1' not found

### ISSUE THREAD

**Issue by rickhelmus** [cbroeckl/RAMClustR#11]
Hello,

Seems a recent commit (2438b68) is resulting in an error if normalize != "quantile" ([ramclustR.R@461](https://github.com/cbroeckl/RAMClustR/blob/1290e107d4d882a08cf6c446b8ff717a806d2fd7/R/ramclustR.R#L461)). 

Thanks,
Rick

**Comment by cbroeckl** [comment]
Thanks Rick,

I believe I have addressed this issue, adding a normalize=="quantile" statement to ramclustR.R@461.  

Corey

**Comment by rickhelmus** [comment]
Hi Corey,

Thanks! This seems to fix it.
