### ISSUE TITLE
temp2 object not found

### ISSUE THREAD

**Issue by rickhelmus** [cbroeckl/RAMClustR#12]
Hi Corey,

Seems a tiny bug was recently introduced at https://github.com/cbroeckl/RAMClustR/blob/47620bf677ea67e0b7d03ccfc10b2633cb0601e2/R/ramclustR.R#L567
Which errors with object 'temp2' not found.

Thanks,
Rick

**Comment by cbroeckl** [comment]
Hello rickhelmus - sorry for the slow response.  I did correct this code bug and it seems to be working well - please let me know if you have any further issues.

**Comment by rickhelmus** [comment]
Great, thanks! I confirm this solves the problem.

**Comment by cbroeckl** [comment]
Fantastic.  You must have recognized the issue using a small-ish sample set.  I have changed the behavior of the algorithm to not use correlations similarity score when there are fewer than five samples.  I did not make this optional, but could if need be.  Feedback is welcome.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rickhelmus** [comment]
Hi Corey,

You're right about the small sample set. It would be interesting to be able to compare both methods at some point. Perhaps a new function argument that can be used to select the method (keeping the current behaviour when not specified) would be good for this.

**Comment by cbroeckl** [comment]
I will place an option in there.   The original algorithm relies heavily on correlational relationships, and I have never trusted that it works well with low n, but I rarely use this for low n.  I would appreciate a more detailed description of your observcations. In the interim – I will try to update this function and let you know once I have pushed it to github.  Thanks,

Corey

**Comment by cbroeckl** [comment]
Rick - i just update the ramclustR function to enable optional control over the use of correlational similarity scoring with fewer than 5 samples.

**Comment by rickhelmus** [comment]
Hi Corey,

Many thanks for that! (and sorry for my late reply) I hope to have some more time soon to have a better look at it. 

In general my situation is quite the opposite: it is not unusual that features are only present within a handful of samples, so controlling the behavior will be interesting.

**Comment by cbroeckl** [comment]
hello rick - a nice option for you (given low frequency feature detection) might be to use spearmans rank correlation instead of pearsons.  this is an optional setting in the ramclustR function, but I haven't tested it much.

**Comment by rickhelmus** [comment]
Alright, thanks, that is interesting and will definitely give it a try!
