### ISSUE TITLE
Moving over from xcms issue #430

### ISSUE THREAD

**Issue by Phylloxera** [cbroeckl/RAMClustR#15]
Thanks @cbroeckl for all the help so far,
`RC <- ramclustR(xcmsObj = xdata, ExpDes=experiment)`

> Error in if (!is.null(xcmsObj) & mslev == 2 & any(is.null(MStag), is.null(idMSMStag), :
> missing value where TRUE/FALSE needed
> In addition: Warning message:
> In ramclustR(xcmsObj = xdata, ExpDes = experiment) :
> NAs introduced by coercion

Is this because I filled in something incorrectly at
`experiment <- defineExperiment(csv = FALSE)`?

**Comment by cbroeckl** [comment]
use: 

cat(experiment)
and report the output to the console here please

**Comment by Phylloxera** [comment]
> Error in cat(experiment) : 
  argument 1 (type 'list') cannot be handled by 'cat'

**Comment by cbroeckl** [comment]
sorry just type
experiment

**Comment by Phylloxera** [comment]
> $design
                           Value
Experiment  separate_broeckling1
Species                      sus
Sample                     serum
Contributor               usmarc
platform                   LC-MS
                                             Description
Experiment                    experiment name, no spaces
Species                                     species name
Sample                                       sample type
Contributor individual and/or organizational affiliation
platform                                  GC-MS or LC-MS

> $instrument
>                           value
> chrominst   Waters_Acquity_UPLC
> msinst            Waters_XevoG2
> column                       C8
> solvA                   5%MetOH
> solvB                  95%MetOH
> CE1                           6
> CE2                          30
> mstype                      mse
> msmode                 positive
> ionization             positive
> colgas                 nitrogen
> msscanrange             50-1200
> conevolt                   2200
> MSlevs                      1,2

**Comment by cbroeckl** [comment]
```
## first we will change MSlevs to 2
fix <- which(row.names(experiment[[2]]) == "MSlevs")
experiment[[2]][fix,1] <- 2
```

then when you run ramclustR: 

`
RC <- ramclustR(xcmsObj = xdata, ExpDes=experiment, MStag = "01.mzML", idMSMStag = "02.mzml")
`

**Comment by Phylloxera** [comment]
I changed the command slightly (i must have misread your naming scheme)
```
RC <- ramclustR(xcmsObj = xdata, ExpDes=experiment, 
                MStag = "ms1.mzML", idMSMStag = "ms2.mzml")
```
And it seems to have ran, thanks!

>   organizing dataset 
  normalizing dataset 
calculating ramclustR similarity: nblocks =  3 
1  2  3  
 RAMClust feature similarity matrix calculated and stored: 
RAMClust distances converted to distance object 
fastcluster based clustering complete 
dynamicTreeCut based pruning complete 
RAMClust has condensed 2971 features into 544 spectra 
collapsing feature into spectral signal intensities 
writing msp formatted spectra 
msp file complete

**Comment by hechth** [comment]
@Phylloxera so you can confirm that this problem was fixed?  Then we can actually close this here :)

Thanks!
