### ISSUE TITLE
Make RAMClustR available on CRAN

### ISSUE THREAD

**Issue by martenson** [cbroeckl/RAMClustR#16]
Hi, is there an intent to revitalize the CRAN package for this tool? The official page says it has been removed from CRAN and only archive with old versions is available.

https://cran.r-project.org/web/packages/RAMClustR/index.html

**Comment by cbroeckl** [comment]
I do intend to get back on CRAN.  in the interim, please consider using the github version.   Sorry for the slow response - i didn't receive any notification of an open issue (probably email filtering is to blame).

**Comment by martenson** [comment]
@cbroeckl Thanks for getting back. For the moment I've wrapped the last version archived at CRAN (1.0.9) for Conda. It is available in the bioconda channel here: https://bioconda.github.io/recipes/r-ramclustr/README.html

**Comment by martenson** [comment]
Thanks for making this happen @cbroeckl ! 

https://cran.r-project.org/web/packages/RAMClustR/index.html

**Comment by cbroeckl** [comment]
> @cbroeckl Thanks for getting back. For the moment I've wrapped the last version archived at CRAN (1.0.9) for Conda. It is available in the bioconda channel here: https://bioconda.github.io/recipes/r-ramclustr/README.html

my pleasure - only took 6 months!!  hopefully i can keep it on CRAN now - still honing my 'developer' skillset.

**Comment by martenson** [comment]
The updated version is now also available as a package on Conda: https://anaconda.org/bioconda/r-ramclustr
