### ISSUE TITLE
exportDataset function fails due to `getData` function not being found

### ISSUE THREAD

**Issue by hechth** [cbroeckl/RAMClustR#17]
Trying to use the `exportDataset` function from the library, I run into an error where the `getData` function mentioned below is not found.

https://github.com/cbroeckl/RAMClustR/blob/eb15f37a77bac25fb59c90e5b212169464de62f2/R/exportDataset.R#L27-L32

Which function is this or is the `exportDataset` function deprecated?

I'm very thankful for any advice.

**Comment by cbroeckl** [comment]
@hechth - sorry for the delay.  i was doing a bit of cleanup and got a bit sloppy in removing this function.  it was still present in more an internal package i maintain, so i failed to  notice this error.  

I have just reinstated this in the github version a few minutes ago.   thanks for catching it!

**Comment by hechth** [comment]
@cbroeckl Thank you for pointing that out and fixing it! :)
