### ISSUE TITLE
suspected write problem in RAMClustR::write.msp

### ISSUE THREAD

**Issue by martenson** [cbroeckl/RAMClustR#18]
As part of our wrapping of RAMClustR in Galaxy, we are routinely running a fairly basic test described below. After switching from 1.0.9 to 1.2.1 we are experiencing the following error:

```
Error in round(ramclustObj$clri[i], 2) : 
  non-numeric argument to mathematical function
Calls: store_output -> <Anonymous> -> paste0
Execution halted
```

Our store_output function calls the `RAMClustR::write.msp` [here](https://github.com/RECETOX/galaxytools/blob/master/tools/ramclustr/ramclustr_wrapper.R#L9)

@hechth suspects that new version of RAMClustR does not expect a parameter to be missing

The parameters of the test are [here](https://github.com/RECETOX/galaxytools/blob/master/tools/ramclustr/ramclustr.xml#L113)
The input file is [here](https://github.com/RECETOX/galaxytools/blob/master/tools/ramclustr/test-data/csv_test-input_1_2.csv)

**Comment by hechth** [comment]
I did some follow-up and seems like `x$clri` is Null, therefore it can't be passed to the `round(...)` function.

The input data doesn't contain retention indices. I'll be happy to try to contribute a possible fix for this problem :).

**Comment by martenson** [comment]
@cbroeckl Could you please give us some feedback on this issue?

**Comment by cbroeckl** [comment]
@martenson 
My apologies - i need to figure out why i am not getting notifications!  I will get this fixed shortly.

**Comment by cbroeckl** [comment]
@martenson 
I believe that this should pass your Galaxy check now.  I also believe i figured out how to have Github notifiy when an issue is created or commented on.   Win.

**Comment by cbroeckl** [comment]
@martenson @hechth  - updated ramclustr is on its way to CRAN.

**Comment by martenson** [comment]
This is awesome! Many thanks @cbroeckl!

**Comment by martenson** [comment]
Seems to work as advertised. Many thanks!
