### ISSUE TITLE
Implement a test case using individual steps to build the whole `ramclust.R` workflow

### ISSUE THREAD

**Issue by hechth** [cbroeckl/RAMClustR#30]
Since the main [ramclustR.R](R/ramclustR.R) file has become somewhat obsolete with the new individual components, it would be good to mark it as deprecated or even remove the functionality from the package after making sure that everything is kept where it actually should be. Another option would be to have this function as a _default_ workflow running the fundamental steps of RAMClustR, so keeping it intact as a main wrapper @cbroeckl ?

To make sure that the functionality is kept or equivalent, we need a test case which runs the individual steps and then we can make a comparison to the results created by the old `ramclustR` function.

**Comment by cbroeckl** [comment]
I am reluctant to deprecate unless we know how people are using it.  It would be good to keep it around until we can cofirm that we can get similar output using the rc.ramclustr.R or further 'chunked' function.  Correct me if i am wrong, but you have been using the original ramclustR.R function, correct?

**Comment by hechth** [comment]
> I am reluctant to deprecate unless we know how people are using it.  It would be good to keep it around until we can cofirm that we can get similar output using the rc.ramclustr.R or further 'chunked' function.  Correct me if i am wrong, but you have been using the original ramclustR.R function, correct?  

Yeah, our Galaxy tool actually also uses this. Then let's agree on providing it as a wrapper and let's try to get the same output using the individual rc. functions?

**Comment by cbroeckl** [comment]
i think that what makes the most sense is to keep it as the main function, but as a wrapper.  once we can get the old and new chunked version to get the same output, we can start working on building in the functionality in the rc.### functions.

**Comment by hechth** [comment]
So lets replace the ramclustR function code with the calls to those steps - we have already implemented a test and the results are the same within the tolerance.

**Comment by cbroeckl** [comment]
what is the 'tolerance'?

**Comment by hechth** [comment]
+- 10 values on intensity of detected features and mz differences in 5th digit after the comma in deconvoluted spectra - and in our test data one extra deconvoluted spectrum appears (569 instead of 568). Number of peaks in each spectrum is excatly the same - so mostly small numeric differences.
