### ISSUE TITLE
Error in define_samples(ramclustObj, blank.tag)

### ISSUE THREAD

**Issue by arpita-007** [cbroeckl/RAMClustR#50]
Hi,
I am getting this new error which I don't know the reason for. I have been using RAMClustR the same way as I have been using it before. Suddenly this error came up.

Error in define_samples(ramclustObj, blank.tag) : 
  no Blanksample.names.sample_group samples found using the tag 'Blanksample.names.sample_group'

Can you please help me to resolve this?

**Comment by hechth** [comment]
@arpita-007 which version of RAMClustR are you using and can you post also your input data so we can reproduce the error? Thanks!

**Comment by hechth** [comment]
@arpita-007 does this problem still persist? What blank tag did you choose? Otherwise can we close this issue?

**Comment by arpita-007** [comment]
@hechth Hi, yes, please. You can close this issue.
Thank you!
