### ISSUE TITLE
Error: unused argument (fftempdir = fftempdir)

### ISSUE THREAD

**Issue by brooklynnrm** [cbroeckl/RAMClustR#51]
Hello, I have been trying to use the ramclustr function for deconvolution of an XCMS feature table. I have tried my own data as well as the example data and everything has thrown the error below:

Error in rc.ramclustr(ramclustObj = ramclustObj, st = st, sr = sr, maxt = maxt,  : 
  unused argument (fftempdir = fftempdir)

My input is:
ure table
gc_feature_table<- read.table("E:/Galaxy/Bacarelli - Additional Samples/Galaxy processing files/XCMS_Test_231017_XCMSv3.22.0_Peak.min_Peak.max.txt", sep="\t", header=TRUE)

#create mz_time vector
mz_time<- paste(gc_feature_table$mz, gc_feature_table$rt, sep="_")
mz_time[1:10]

#transcribe intensities
t_gc_int<- data.frame(t(gc_feature_table[,10:ncol(gc_feature_table)]))

#add mz_time vector to transcribed matrix
t_gc_int_1<- rbind(mz_time,t_gc_int)

#add sample_id vector to transcribed matrix
sample_id<- c("sample",rownames(t_gc_int))
t_gc_int_2<- cbind(sample_id,t_gc_int_1)
t_gc_int_23 <- t_gc_int_2[1:10,1:20]

#write output
setwd("E:/XCMS Projects/RamClustR/")
write.table(t_gc_int_23, "XCMS_Test_231018_RAMClustR.csv", sep=",", row.names=FALSE, col.names=FALSE)

library(RAMClustR)

out_file<- "E:/XCMS Projects/RamClustR/"
dir.create(out_file)
setwd(out_file)

experiment_GC <- defineExperiment(csv = "E:/XCMS Projects/RamClustR/ExpDes.csv")

GC_Clust <- ramclustR(ms = "E:/XCMS Projects/RamClustR/XCMS_Test_231018_RAMClustR.csv", 
                          featdelim = "_", 
                          st = 5, 
                          ExpDes=experiment_GC, 
                          sampNameCol = 1, minModuleSize=1, mzdec=5, fftempdir = NULL)

**Comment by cbroeckl** [comment]
@brooklynnrm  - what is the error message you receive? 

can you also add the output from sessionInfo()?

**Comment by brooklynnrm** [comment]
<html>
<body>


R version 4.3.1 (2023-06-16 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 19045)  Matrix products: default   locale: [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 [4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8      time zone: America/New_York tzcode source: internal  attached base packages: [1] stats4    stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] scatterplot3d_0.3-44      corpcor_1.6.10            JADE_2.0-4                waveslim_1.8.4             [5] WaveICA_0.1.0             InterpretMSSpectrum_1.3.8 ggplot2_3.4.4             pcaMethods_1.92.0          [9] gplots_3.1.3              e1071_1.7-13              preprocessCore_1.62.1     fastcluster_1.2.3         [13] RCurl_1.98-1.12           curl_5.1.0                stringi_1.7.12            testthat_3.2.0            [17] BiocManager_1.30.22       xcms_3.22.0               MSnbase_2.26.0            ProtGenerics_1.32.0       [21] S4Vectors_0.38.2          mzR_2.34.1                Rcpp_1.0.11               Biobase_2.60.0            [25] BiocGenerics_0.46.0       BiocParallel_1.34.2       rmarkdown_2.25            knitr_1.44                [29] dynamicTreeCut_1.63-1     RAMClustR_1.3.0            loaded via a namespace (and not attached):  [1] bitops_1.0-7                pROC_1.18.4                 gridExtra_2.3               fdrtool_1.2.17               [5] rlang_1.1.1                 magrittr_2.0.3              clue_0.3-65                 snakecase_0.11.1             [9] MassSpecWavelet_1.66.0      matrixStats_1.0.0           compiler_4.3.1              vctrs_0.6.4                 [13] stringr_1.5.0               pkgconfig_2.0.3             crayon_1.5.2                fastmap_1.1.1               [17] XVector_0.40.0              caTools_1.18.2              utf8_1.2.3                  ggfortify_0.4.16            [21] purrr_1.0.2                 xfun_0.40                   zlibbioc_1.46.0             GenomeInfoDb_1.36.4         [25] DelayedArray_0.26.7         parallel_4.3.1              cluster_2.1.4               R6_2.5.1                    [29] RColorBrewer_1.1-3          limma_3.56.2                brio_1.1.3                  GenomicRanges_1.52.1        [33] lubridate_1.9.3             SummarizedExperiment_1.30.2 iterators_1.0.14            IRanges_2.34.1              [37] Matrix_1.6-1.1              splines_4.3.1               timechange_0.2.0            tidyselect_1.2.0            [41] rstudioapi_0.15.0           abind_1.4-5                 doParallel_1.0.17           codetools_0.2-19            [45] affy_1.78.2                 lattice_0.21-8              tibble_3.2.1                plyr_1.8.9                  [49] withr_2.5.1                 evaluate_0.22               survival_3.5-5              proxy_0.4-27                [53] pillar_1.9.0                affyio_1.70.0               MatrixGenerics_1.12.3       KernSmooth_2.23-22          [57] foreach_1.5.2               MALDIquant_1.22.1           ncdf4_1.21                  generics_0.1.3              [61] munsell_0.5.0               scales_1.2.1                gtools_3.9.4                class_7.3-22                [65] glue_1.6.2                  janitor_2.2.0               MsFeatures_1.8.0            tools_4.3.1                 [69] plsdepot_0.2.0              mzID_1.38.0                 robustbase_0.99-0           enviPat_2.6                 [73] vsn_3.68.0                  RANN_2.6.1                  XML_3.99-0.14               grid_4.3.1                  [77] impute_1.74.1               tidyr_1.3.0                 MsCoreUtils_1.12.0          colorspace_2.1-0            [81] GenomeInfoDbData_1.2.10     cli_3.6.1                   fansi_1.0.5                 S4Arrays_1.0.6              [85] dplyr_1.1.3                 gtable_0.3.4                DEoptimR_1.1-3              digest_0.6.33               [89] htmltools_0.5.6.1           multtest_2.56.0             lifecycle_1.0.3             MASS_7.3-60
--
 
> | >
>


</body>
</html>

**Comment by brooklynnrm** [comment]
@cbroeckl 
The error is below:

organizing dataset 
replaced 75 of 171 total feature values ( 44 % ) 
  normalizing dataset 
Error in rc.ramclustr(ramclustObj = ramclustObj, st = st, sr = sr, maxt = maxt,  : 
  unused argument (fftempdir = fftempdir)

**Comment by cbroeckl** [comment]
I am fairly certain this is an artifact of a reorganization of code we recently performed.   i would request that you try to install from github, try again, and let me know how it goes.

detach('package:RAMClustR')
devtools::install_github("cbroeckl/RAMClustR",  dependencies = FALSE)

**Comment by brooklynnrm** [comment]
I just re-installed and tried again. Still getting the error:

Error in rc.ramclustr(ramclustObj = ramclustObj, st = st, sr = sr, maxt = maxt,  : 
  unused argument (fftempdir = fftempdir)

**Comment by cbroeckl** [comment]
alright - just pushed an edit. i think i found the reference causing the problem.   Please try again.  if this doesn't fix the issue i will ask for input files and will try to replicate the error here first.

**Comment by cbroeckl** [comment]
detach('package:RAMClustR')
devtools::install_github("cbroeckl/RAMClustR", dependencies = FALSE)

**Comment by brooklynnrm** [comment]
Thank you so much for your help! This has fixed the issue!
