### ISSUE TITLE
No disk space while calling "ff" in ramclustR.R:263

### ISSUE THREAD

**Issue by tsufz** [cbroeckl/RAMClustR#9]
Hi Steffen,
RAMClustR uses ffmat<-ff(vmode="double", dim=c(n, n), initdata = 0) to call ff in ramclustR.R:263. ff obviously uses the default temp folder to store temporary files. In cases of limited space in the user profile, the call of ff may fail if no more empty disk space could be allocated. In a server based (HPC) environment this could happen, because user profile space is maybe limited and the working directory is allocated on scratch devices. We had a problem on Windows Server 2012 with the user profile located on C:/ and a quota of 10 GB and a working directory on scratch S:/.

I suggest to change the call of ff such that the temp files generated by ff are allocated in the working space and not in the system temp space.

A work around is to set the user system variables of the temp directory to a folder with enough space.

Yours,
Tobias

**Comment by cbroeckl** [comment]
Hello Tobias,
I just added an argument enabling setting of the ffttempdir.  Thanks,
Corey
